export const GET_WALLET_ADDRESS = 'GET_WALLET_ADDRESS';
export const GET_WALLET_ADDRESS_SUCCESS = 'GET_WALLET_ADDRESS_SUCCESS';
export const GET_WALLET_ADDRESS_FAILURE = 'GET_WALLET_ADDRESS_FAILURE';

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_AUTH_TOKEN_SUCCESS = 'SET_AUTH_TOKEN_SUCCESS';
export const SET_AUTH_TOKEN_FAILED = 'SET_AUTH_TOKEN_FAILED';

export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_FAILED = 'SET_PROFILE_FAILED';
